name: R CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-r-script:
    runs-on: windows-latest  # 使用Windows环境
    timeout-minutes: 60  # 设置超时时间为60分钟

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.1'  # 可以根据需要修改R版本

    - name: Set up Rtools
      run: |
        choco install rtools -y
        writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")

    - name: Install dependencies
      run: |
        install.packages("remotes")
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\Documents\R\win-library
        key: ${{ runner.os }}-r-${{ hashFiles('**/*.lock') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Run R script
      run: |
        Rscript data_analysis.R  # 执行上传的R脚本
      shell: Rscript {0}
